name: proba_env
on:
  push:
    paths:
      - '.github/workflows/proba_env.yml'
jobs:
  proba:
    runs-on: ubuntu-latest
    steps:
      - name: Zapis do GITHUB_ENV
        run: echo "JADRO2=$(uname -r)" >> $GITHUB_ENV
      - name: Warunek na env
        if: startsWith(env.JADRO2, '6.')
        run: echo "warunek na env.JADRO2 dziala"
      - name: Wyrazenie z env
        run: echo "wartosc z wyrazenia ${{ env.JADRO2 }}"
