name: proba_warunki
on:
  push:
    paths:
      - '.github/workflows/proba_warunki.yml'
jobs:
  testy_warunku:
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz wersje jadra
        id: jadro_kroku
        run: |
          KERNEL=$(uname -r)
          echo "KERNEL=$KERNEL" >> $GITHUB_OUTPUT

      - name: Celowy blad
        run: exit 1

      - name: Wyswietl informacje jesli jadro jest 6.x
        if: startsWith(steps.jadro_kroku.outputs.KERNEL, '6.')
        run: echo "6.x"

      - name: Uruchom zawsze
        if: always()
        run: echo "Zawsze"

      - name: Uruchom po awarii
        if: failure()
        run: echo "Po awarii"

      - name: Uruchom po sukcesie
        if: success()
        run: echo "Po sukcesie"

      - name: Bez warunku
        run: echo "Bez warunku"

      - name: Warunek startsWith po awarii
        if: failure() && startsWith(steps.jadro_kroku.outputs.KERNEL, '6.')
        run: echo "po awarii i 6.x"

  drugie_zadanie:
    runs-on: ubuntu-latest
    needs: testy_warunku
    if: failure()
    steps:
      - name: Drugie zadanie
        run: echo "Drugie zadanie wykonane"

  trzecie_bez_if:
    runs-on: ubuntu-latest
    needs: testy_warunku
    steps:
      - run: echo "trzecie"
